<?php

namespace app\controllers;

use app\models\BioFileHelper;
use app\models\BlackActions;
use app\models\BlackResponse;
use app\models\BlackResult;
use app\models\db\BioActions;
use app\models\db\BioDistrict;
use app\models\db\BioResponse;
use app\models\db\BioUser;
use app\models\db\BioUserMeasure;
use app\models\db\BioMeasure;
use app\models\db\BioUserPacient;
use app\models\forms\RegistrationForm;
use app\models\forms\UploadForm;
use moonland\phpexcel\Excel;
use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\BaseFileHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\forms\LoginForm;
use app\models\forms\ContactForm;
use yii\web\UploadedFile;

class WidgetController extends Controller
{
    public $user;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'stub', 'about'],
                'rules' => [
                    [
                        'actions' => ['logout', 'stub', 'about'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            /*'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],*/
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->user = BioUser::findByUserId(Yii::$app->user->getId());
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionLogin()
    {

        $user = BioUser::findByUserId(Yii::$app->user->getId());
        $pacient = BioUserPacient::findByUserId(Yii::$app->user->getId());

        /* avatar */
        $avatar = ($user)? BioFileHelper::getMainFile(BioUser::getPhotoPath($user->path_key)) : null;
        //debug($avatar);
        if (!$avatar) $avatar = '/img/main-avatar.png';
        else $avatar = '/' . $avatar;

        return $this->renderAjax('login', [
            'user' => $user,
            'pacient' => $pacient,
            'avatar' => $avatar
        ]);
    }

}
