<?php
namespace app\modules\api\controllers;

use app\modules\api\models\db\BioUser;
use app\modules\api\models\db\BioUserDoctor;
use app\modules\api\models\db\BioUserPacient;
use app\modules\api\models\forms\RegistrationForm;
use app\modules\api\models\forms\LoginForm;
use app\modules\api\models\forms\UploadForm;
use app\modules\api\models\db\BioDoctorPacientConnection;
use yii\base\Theme;
use yii\web\UploadedFile;
use app\modules\api\models\BioFileHelper;
use app\modules\api\models\db\BioNoticeTypes;
use app\modules\api\models\db\BioUserNotice;
use app\modules\api\models\db\BioClinicList;
use app\modules\api\models\db\BioDoctorSchedule;
use app\modules\api\models\db\BioRecordToDoctor;
use app\modules\api\models\db\BioScheduleTemplates;
use Yii;
use yii\imagine\Image;
use Imagine\Image\Box;

class UserController extends _ApiController
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => \yii\filters\Cors::className(),
            'cors' => [
                // restrict access to
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['POST', 'PUT'],
                // Allow only POST and PUT methods
                'Access-Control-Request-Headers' => ['X-Wsse'],
                // Allow only headers 'X-Wsse'
                'Access-Control-Allow-Credentials' => true,
                // Allow OPTIONS caching
                'Access-Control-Max-Age' => 3600,
                // Allow the X-Pagination-Current-Page header to be exposed to the browser.
                'Access-Control-Expose-Headers' => ['X-Pagination-Current-Page'],
            ],
        ];
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        return $behaviors;
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex($access_token)
    {
        $user = BioUser::findByAccessToken($access_token);
        return $user;
    }

    public function actionLogin()
    {
        $model = new LoginForm();
        $model->setAttributes(Yii::$app->request->post());
        if ($model->validate()) {
            return [
                'success' => true,
                'result' => $model->getUser(),
            ];
        } else {
            return [
                'success' => false,
                'result' => $model->errors,
            ];
        }
    }


    public function actionUser()
    {
        if(!empty($this->user)){
            return [
                'success' => true,
                'result' => $this->user->getUserInfoById($this->user->id),
            ];
        } else {
            return [
                'success' => false,
            ];
        }
    }

    public function actionRegister()
    {
        switch (Yii::$app->request->post('type')){
            case 'doctor':
                $scenario = 'doctor';
                break;
            case 'pacient':
                $scenario = 'pacient';
                break;
            case 'partner':
                $scenario = 'partner';
                break;
            default:
                $scenario = 'pacient';
        }
        $model = new RegistrationForm(['scenario' => $scenario]);
        $model->setAttributes(Yii::$app->request->post());

        $time = time();
        $user = new BioUser();
        $user->setAttributes([
            'email' => $model->email,
            'name' => $model->name,
            'patronymic' => $model->patronymic,
            'surname' => $model->surname,
            'phone' => $model->phone,
            'passwd' => md5($model->password),
            'type' => $model->type,
            'status' => 1,
            'created' => $time,
            'updated' => $time,
            'auth_key' => uniqid("", rand(1000, 9999)),
            'access_token' => md5(md5(uniqid(rand(), 1)) . md5($model->email)),
            'path_key' => md5($model->email),
        ]);

        if ($model->validate() && $user->validate() && $model->register()) {
            return [
                'success' => true,
                'result' => $model->getUserInfo(),
            ];
        } else {
            return [
                'success' => false,
                'result' => array_merge($model->getErrors(), $user->getErrors())
            ];
        }
    }

    public function actionEdituser()
    {
        if (!empty($this->user)) {
            switch (Yii::$app->request->post('type')){
                case 'doctor':
                    $scenario = 'doctor_edit';
                    break;
                case 'pacient':
                    $scenario = 'pacient_edit';
                    break;
                case 'partner':
                    $scenario = 'partner_edit';
                    break;
                default:
                    $scenario = 'pacient_edit';
            }
            $model = new RegistrationForm(['scenario' => $scenario]);
            $model->setAttributes(Yii::$app->request->post());
            if($model->validate() && $model->updateUserById($this->user->id, Yii::$app->request->post())){
                return [
                    'success' => true,
                    'result' => $this->user->getUserInfoById($this->user->id),
                ];
            } else {
                return [
                    'success' => false,
                    'result' => $model->getErrors(),
                ];
            }

        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionUpload()
    {
        if (!empty($this->user)) {
            if (Yii::$app->request->isPost) {
                $dir = BioUser::getPhotoPath($this->user->path_key);
                $filePath = Yii::getAlias('@app').'/uploads'.$dir;
                BioFileHelper::deleteMainSymbols($filePath); // create if not exist inside
                $file = explode('.', $_FILES["file"]["name"]);
                $filesToDel = scandir($filePath);
                foreach ($filesToDel as $fileToDel){
                    if(strlen($fileToDel) > 2) {
                        unlink($filePath . '/' . $fileToDel);
                    }
                }
                if (copy($_FILES["file"]["tmp_name"], $filePath . '/user_avatar_big_'.$this->user->id.'.'.$file[1])) {
                    $photo = Image::getImagine()->open($filePath . '/user_avatar_big_'.$this->user->id.'.'.$file[1]);
                    $photo->thumbnail(new Box(59, 59))->save($filePath. '/user_avatar_min_'.$this->user->id.'.'.$file[1], ['quality' => 90]);
                    return [
                        'success' => true,
                    ];
                } else {
                    return [
                        'success' => false,
                    ];
                }
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionCreateconnectionrequest()
    {
        if (!empty($this->user)) {
            $model = new BioDoctorPacientConnection();
            $model->setAttributes(Yii::$app->request->post());
            $existing = $model->findByPacientAndDoctor();

            if(!empty($existing) && $existing->approved = 1){
                return [
                    'success' => false,
                    'result' => 'Connect already exist'
                ];
            } elseif(!empty($existing) && $existing->approved = 2){
                $existing->approved = 0;
                $existing->initiator = $this->user->id;
                $existing->save();

                $notice = new BioUserNotice();
                $notice->user_id = $this->user->id == Yii::$app->request->post('pacient_id') ? Yii::$app->request->post('doctor_id') : Yii::$app->request->post('pacient_id');
                $notice->read = 0;
                $notice->notice_type_id = 1;
                $notice->c_time = new \yii\db\Expression('NOW()');
                $notice->extra_data = json_encode(['pacient_id' => Yii::$app->request->post('pacient_id'), 'doctor_id' => Yii::$app->request->post('doctor_id')]);
                $notice->save();

                return [
                    'success' => true,
                    'result' => $existing->attributes
                ];
            }

            if ($model->validate()) {
                if(!in_array($this->user->id, array(Yii::$app->request->post('doctor_id'), Yii::$app->request->post('pacient_id')))){
                    return [
                        'success' => false,
                        'result' => 'You do not have permission'
                    ];
                }
                $model->initiator = $this->user->id;
                $model->save();

                $notice = new BioUserNotice();
                $notice->user_id = $this->user->id == Yii::$app->request->post('pacient_id') ? Yii::$app->request->post('doctor_id') : Yii::$app->request->post('pacient_id');
                $notice->read = 0;
                $notice->notice_type_id = 1;
                $notice->c_time = new \yii\db\Expression('NOW()');
                $notice->extra_data = json_encode(['pacient_id' => Yii::$app->request->post('pacient_id'), 'doctor_id' => Yii::$app->request->post('doctor_id')]);
                $notice->save();

                return [
                    'success' => true,
                    'result' => $model->attributes
                ];
            } else {
                return [
                    'success' => false,
                    'result' => $model->getErrors(),
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionDisconnectpacientfromdoctor()
    {
        if (!empty($this->user)) {
            $model = new BioDoctorPacientConnection();
            $model->setAttributes(Yii::$app->request->post());
            $result = $model->findByPacientAndDoctor();
            if ($result) {
                if(!in_array($this->user->id, array(Yii::$app->request->post('doctor_id'), Yii::$app->request->post('pacient_id'))) || $result->initiator == $this->user->id){
                    return [
                        'success' => false,
                        'result' => 'You do not have permission'
                    ];
                }
                $result->approved = 2;
                $result->save();

                $notice = new BioUserNotice();
                $notice->user_id = Yii::$app->request->post('doctor_id');
                $notice->read = 0;
                $notice->notice_type_id = 2;
                $notice->c_time = new \yii\db\Expression('NOW()');
                $notice->extra_data = json_encode(['pacient_id' => Yii::$app->request->post('pacient_id'), 'doctor_id' => Yii::$app->request->post('doctor_id')]);
                $notice->save();

                $notice = new BioUserNotice();
                $notice->user_id = Yii::$app->request->post('pacient_id');
                $notice->read = 0;
                $notice->notice_type_id = 2;
                $notice->c_time = new \yii\db\Expression('NOW()');
                $notice->extra_data = json_encode(['pacient_id' => Yii::$app->request->post('pacient_id'), 'doctor_id' => Yii::$app->request->post('doctor_id')]);
                $notice->save();

                return [
                    'success' => true,
                ];
            } else {
                return [
                    'success' => false,
                    'result' => 'Connect does not exist'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionApproveconnection()
    {
        if (!empty($this->user)) {
            $model = new BioDoctorPacientConnection();
            $model->setAttributes(Yii::$app->request->post());
            $result = $model->findByPacientAndDoctor();
            if ($result) {
                if(!in_array($this->user->id, array(Yii::$app->request->post('doctor_id'), Yii::$app->request->post('pacient_id'))) || $result->initiator == $this->user->id){
                    return [
                        'success' => false,
                        'result' => 'You do not have permission'
                    ];
                }
                $result->approved = 1;
                $result->save();

                $notice = new BioUserNotice();
                $notice->user_id = Yii::$app->request->post('doctor_id');
                $notice->read = 0;
                $notice->notice_type_id = 3;
                $notice->c_time = new \yii\db\Expression('NOW()');
                $notice->extra_data = json_encode(['pacient_id' => Yii::$app->request->post('pacient_id'), 'doctor_id' => Yii::$app->request->post('doctor_id')]);
                $notice->save();

                $notice = new BioUserNotice();
                $notice->user_id = Yii::$app->request->post('pacient_id');
                $notice->read = 0;
                $notice->notice_type_id = 3;
                $notice->c_time = new \yii\db\Expression('NOW()');
                $notice->extra_data = json_encode(['pacient_id' => Yii::$app->request->post('pacient_id'), 'doctor_id' => Yii::$app->request->post('doctor_id')]);
                $notice->save();

                return [
                    'success' => true,
                    'result' => $result->attributes
                ];
            } else {
                return [
                    'success' => false,
                    'result' => 'Connect does not exist'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionGetdoctorspacients()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $doctor_id = $this->user->id;
                $condition = [
                    'doctor_id' => $doctor_id,
                    'approved' => ''
                ];

                if(Yii::$app->request->post('approved') != 'all')
                {
                    $condition['approved'] = Yii::$app->request->post('approved');
                } else {
                    unset($condition['approved']);
                }

                $connectionList= BioDoctorPacientConnection::findAll($condition);
                if (!empty($connectionList)) {
                    $pacientList = [];
                    foreach ($connectionList as $connection){
                        $pacientList[$connection->pacient_id] = BioUser::getUserInfoById($connection->pacient_id);
                        $pacientList[$connection->pacient_id]['pacient_info']['approved'] = $connection->approved;
                    }
                    return [
                        'success' => true,
                        'result' => $pacientList
                    ];
                } else {
                    return [
                        'success' => false,
                        'result' => 'doctor_id can not be blank'
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'No results'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionGetpacientdoctors()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'pacient') {
                $condition = [
                    'pacient_id' => $this->user->id,
                    'enabled' => ''
                ];

                if(Yii::$app->request->post('enabled') != 'all')
                {
                    $condition['enabled'] = Yii::$app->request->post('enabled');
                } else {
                    unset($condition['enabled']);
                }

                $connectionList= BioDoctorPacientConnection::findAll($condition);
                if (!empty($connectionList)) {
                    $doctorList = [];
                    foreach ($connectionList as $connection){
                        $doctorList[$connection->doctor_id] = BioUser::getUserInfoById($connection->doctor_id);
                    }
                    return [
                        'success' => true,
                        'result' => $doctorList
                    ];
                } else {
                    return [
                        'success' => false,
                        'result' => 'doctor_id can not be blank'
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'No results'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionGetusernotices()
    {
        if (!empty($this->user)) {
            $condition = [
                'user_id' => $this->user->id,
                'read' => ''
            ];
            if(Yii::$app->request->post('read') != 'all')
            {
                $condition['read'] = Yii::$app->request->post('read');
            } else {
                unset($condition['read']);
            }

            $notices = BioUserNotice::findAll($condition);
            $result = [];
            if(!empty($notices)){
                foreach ($notices as $notice){
                    $data['read'] = $notice->read;
                    $data['notice_id'] = $notice->notice_id;
                    $data['notice_type'] = BioNoticeTypes::findOne(['notice_type_id' => $notice->notice_type_id])->name;
                    $data['extra_data'] = json_decode($notice->extra_data, true);
                    $data['c_time'] = $notice->c_time;
                    $result[$notice->notice_id] = $data;
                }
            }
            return [
                'success' => true,
                'result' => $result
            ];
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionDeleteusernotice()
    {
        if (!empty($this->user)) {
            if (!empty(Yii::$app->request->post('notice_id'))) {
                $notice = BioUserNotice::findOne(['notice_id' => Yii::$app->request->post('notice_id')]);
                if(!empty($notice)){

                    if(!in_array($this->user->id, array($notice->user_id))){
                        return [
                            'success' => false,
                            'result' => 'You do not have permission'
                        ];
                    }

                    if($notice->delete()){
                        return [
                            'success' => true,
                        ];
                    } else {
                        return [
                            'success' => false,
                            'result' => 'Notice not deleted'
                        ];
                    }
                } else {
                    return [
                        'success' => false,
                        'result' => 'Notice does not exist'
                    ];
                }

            } else {
                return [
                    'success' => false,
                    'result' => 'Notice does not exist'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionSetnoticeread()
    {
        if (!empty($this->user)) {
            if (!empty(Yii::$app->request->post('notice_id'))) {
                $notice = BioUserNotice::findOne(['notice_id' => Yii::$app->request->post('notice_id')]);
                if(!empty($notice)){

                    if(!in_array($this->user->id, array($notice->user_id))){
                        return [
                            'success' => false,
                            'result' => 'You do not have permission'
                        ];
                    }

                    $notice->read = 1;
                    if($notice->update()){
                        return [
                            'success' => true,
                        ];
                    } else {
                        return [
                            'success' => false,
                            'result' => 'Notice not deleted'
                        ];
                    }
                } else {
                    return [
                        'success' => false,
                        'result' => 'Notice does not exist'
                    ];
                }

            } else {
                return [
                    'success' => false,
                    'result' => 'Notice does not exist'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionFindUsersByFio()
    {
        if (!empty($this->user)) {
            $sql = "SELECT bu.id FROM bio_user bu WHERE (CONCAT_WS(' ',bu.surname, bu.name, bu.patronymic) LIKE '%" . Yii::$app->request->post('find') . "%' OR bu.id='" . Yii::$app->request->post('find'). "') AND bu.type='pacient'";
            $search = BioUser::findBySql($sql)->all();
            $result = [];
            if(!empty($search)){
                foreach ($search as $user){
                    $result[$user->id] = BioUser::getUserInfoById($user->id);
                }
            }
            if(count($result) > 0){
                return [
                    'success' => true,
                    'result' => $result
                ];
            } else {
                return [
                    'success' => true,
                    'result' => 'no results'
                ];
            }

        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionDeleteSchedule()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $schedule = BioDoctorSchedule::deleteAll(['schedule_id' => Yii::$app->request->post('schedule_id'), 'doctor_id' => $this->user->id]);
                if($schedule){
                    return [
                        'success' => true,
                    ];
                } else {
                    return [
                        'success' => false,
                        'result' => "You don't have schedule for this date"
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionEditSchedule()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $schedule = BioDoctorSchedule::find()->where(['schedule_id' => Yii::$app->request->post('schedule_id'), 'doctor_id' => $this->user->id])->one();
                if(!empty($schedule)){
                    $schedule->setAttributes(Yii::$app->request->post());
                    if ($schedule->validate()) {
                        if($schedule->update()){
                            BioRecordToDoctor::deleteAll(['schedule_id' =>$schedule->schedule_id]);
                            $workTime = (strtotime($schedule->end_time) - strtotime($schedule->start_time)) / 60;
                            $sessionCount = round($workTime / $schedule->reception_time);
                            for ($i = 1; $i <= $sessionCount; $i++) {
                                $session = new BioRecordToDoctor();
                                $session->end_time = date('Y-m-d H:i:s', strtotime($schedule->start_time) + ($i * $schedule->reception_time * 60));
                                $session->start_time = date('Y-m-d H:i:s', strtotime($session->end_time) - ($schedule->reception_time * 60));
                                $session->schedule_id = $schedule->schedule_id;
                                $session->save();
                            }
                            return [
                                'success' => true,
                                'result' => [
                                    'info' => $schedule->attributes
                                ]
                            ];
                        } else {
                            return [
                                'success' => false,
                                'result' => 'Schedule does not exists'
                            ];
                        }
                    } else {
                        return [
                            'success' => false,
                            'result' => $schedule->getErrors(),
                        ];
                    }

                } else {
                    return [
                        'success' => false,
                        'result' => "You don't have schedule for this date"
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission to make schedule'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionCreateSchedule()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $schedule = new BioDoctorSchedule();
                $schedule->setAttributes(Yii::$app->request->post());
                $schedule->doctor_id = $this->user->id;
                if ($schedule->validate()) {
                    if($schedule->save()){
                        $workTime = (strtotime($schedule->end_time) - strtotime($schedule->start_time)) / 60;
                        $sessionCount = round($workTime / $schedule->reception_time);
                        for ($i = 1; $i <= $sessionCount; $i++) {
                            $session = new BioRecordToDoctor();
                            $session->end_time = date('Y-m-d H:i:s', strtotime($schedule->start_time) + ($i * $schedule->reception_time * 60));
                            $session->start_time = date('Y-m-d H:i:s', strtotime($session->end_time) - ($schedule->reception_time * 60));
                            $session->schedule_id = $schedule->schedule_id;
                            $session->save();
                        }
                        return [
                            'success' => true,
                            'result' => [
                                'info' => $schedule->attributes
                            ]
                        ];
                    } else {
                        return [
                            'success' => false,
                            'result' => 'Schedule does not exists'
                        ];
                    }
                } else {
                    return [
                        'success' => false,
                        'result' => $schedule->getErrors(),
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission to make schedule'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionGetDaySchedule()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $schedules = BioDoctorSchedule::find()->where(['reception_date' => Yii::$app->request->post('reception_date'), 'doctor_id' => $this->user->id])->all();
                if(!empty($schedules)){
                    $schedule_ids = [];
                    $info = [];
                    if(count($schedules) > 0){
                        foreach ($schedules as $schedule){
                            $schedule_ids[] = $schedule->schedule_id;
                            $info[$schedule->schedule_id] = $schedule->attributes;
                            $info[$schedule->schedule_id]['clinic_name'] = BioRecordToDoctor::getClinicNameByScheduleId($schedule->schedule_id);
                            $info[$schedule->schedule_id]['start_time_formated'] = date('H:i', strtotime($schedule->start_time));
                            $info[$schedule->schedule_id]['end_time_formated'] = date('H:i', strtotime($schedule->end_time));
                        }
                    }
                    return [
                        'success' => true,
                        'result' => [
                            'schedule' => BioRecordToDoctor::getFullSchedule($schedule_ids),
                            'info' => $info
                        ]
                    ];
                } else {
                    return [
                        'success' => false,
                        'result' => "You don't have schedule for this date"
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionDeleteTemplate()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $template = BioScheduleTemplates::deleteAll(['template_id' => Yii::$app->request->post('template_id'), 'doctor_id' => $this->user->id]);
                var_dump($template);
                if ($template) {
                    return [
                        'success' => true,
                    ];
                } else {
                    return [
                        'success' => false,
                        'result' => 'Template does not exists'
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionGetScheduleTemplateData()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $template =  BioScheduleTemplates::find()->where(['template_id' => Yii::$app->request->post('template_id'), 'doctor_id' => $this->user->id])->one();
                if(!empty($template)){
                    $schedules = BioDoctorSchedule::find()->where(['reception_date' => $template->link_date, 'doctor_id' => $this->user->id])->all();
                    $info = [];
                    if(count($schedules)> 0){
                        foreach ($schedules as $schedule){
                            $info[$schedule->schedule_id] = $schedule->attributes;
                            $info[$schedule->schedule_id]['clinic_name'] = BioRecordToDoctor::getClinicNameByScheduleId($schedule->schedule_id);
                            $info[$schedule->schedule_id]['start_time_formated'] = date('H:i', strtotime($schedule->start_time));
                            $info[$schedule->schedule_id]['end_time_formated'] = date('H:i', strtotime($schedule->end_time));
                        }
                        return [
                            'success' => true,
                            'result' => [
                                'info' => $info
                            ]
                        ];
                    } else {
                        return [
                            'success' => false,
                            'result' => 'Schedule does not exists'
                        ];
                    }
                } else {
                    return [
                        'success' => false,
                        'result' => 'Template does not exists'
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionGetDoctorsScheduleTemplates()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $templates =  BioScheduleTemplates::find()->where(['doctor_id' => $this->user->id])->all();
                if(count($templates) > 0){
                    $result = [];
                    foreach ($templates as $template){
                        $result[] = $template->attributes;
                    }
                    return [
                        'success' => true,
                        'result' => $result
                    ];
                } else {
                    return [
                        'success' => false,
                        'result' => 'You do not have templates'
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }

    public function actionMakeScheduleTemplate()
    {
        if (!empty($this->user)) {
            if ($this->user->type == 'doctor') {
                $schedules = BioDoctorSchedule::find()->where(['reception_date' => Yii::$app->request->post('link_date'), 'doctor_id' => $this->user->id])->all();
                if(count($schedules) > 0){
                    $template = new BioScheduleTemplates();
                    $template->doctor_id = $this->user->id;
                    $template->template_name = Yii::$app->request->post('template_name');
                    $template->link_date = Yii::$app->request->post('link_date');
                    if($template->validate()){
                        $template->save();
                        return [
                            'success' => true,
                        ];
                    } else {
                        return [
                            'success' => false,
                            'result' => $template->getErrors(),
                        ];
                    }
                } else {
                    return [
                        'success' => false,
                        'result' => 'You do not have schedule for this date'
                    ];
                }
            } else {
                return [
                    'success' => false,
                    'result' => 'User does not have permission'
                ];
            }
        } else {
            return [
                'success' => false,
                'result' => 'User does not exist'
            ];
        }
    }
}